# Start typing your program below this line...
print("Hello there!I'm Babble Bot!")
print("What's your name?")
myName= input ()
print("It is so very nice to meet you, " + myName + ".")
print("How about we get to know each other better, " + myName + "." + " What's your favorite color?")
favColor= input ()
print(favColor + "?" + " That's a beautiful color! I can't pick...they are all so pretty!")
print("What about your favorite movie genre?")
favMovie= input ()
print("I really enjoy" + " " + favMovie + " " + "too." + " I'd have to say my favorite is... horror. Even though I hide behind my hands the whole time!")
print("Final question and I'll stop interrogating you haha! If you could have any pet animal, real or not, what would it be?")
favAnimal= input ()
print("You would choose a" + " " + favAnimal + "?" + " That's awesome! I could definitely see it. What animal could you see me picking?")
myAnimal= input ()
print("Really? I would love to have a" + " " + myAnimal + " " + "as a pet! Great pick.")
print("It was so nice to meet you, " + myName + "." + " I hope you have the most beautiful, wonderful day and don't forget to smile!")